apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bidv-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: filestore-nfs-pv
  resources:
    requests:
      storage: 100Gi